"""Fixed description templating.

The description is no longer free-generated by the LLM: it is read from a file
(``prompts/description/<name>.md``), with ``{title}`` substituted and, when
``DESCRIPTION_VARIABLES`` is enabled, optional ``{theme}`` / ``{occasion}`` /
``{audience}`` slots filled from the vision analysis. Swapping the file changes
the copy with no code change.
"""

from __future__ import annotations

from pathlib import Path

_DESC_DIR = Path(__file__).parent / "prompts" / "description"


def load_description_template(name: str = "default", base_dir: Path | None = None) -> str:
    return ((base_dir or _DESC_DIR) / f"{name}.md").read_text(encoding="utf-8").strip()


def render_description(
    template: str, *, title: str, variables: dict[str, str] | None = None
) -> str:
    out = template.replace("{title}", title)
    for key, value in (variables or {}).items():
        out = out.replace("{" + key + "}", value)
    return out
