"""Application settings, loaded from environment / .env.

Secrets are never hardcoded here — only read from the environment (see CLAUDE.md).
"""

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Runtime configuration for the backend."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    app_env: str = "development"

    # Database (async URL, e.g. postgresql+asyncpg://...).
    database_url: str = "postgresql+asyncpg://etsy:change-me@postgres:5432/etsy_assistant"

    # Redis / arq broker.
    redis_url: str = "redis://redis:6379/0"

    # Security — used later for encrypted token storage. Never logged or returned.
    secret_key: str = "change-me"
    encryption_key: str = "change-me"

    # Etsy Open API v3 credentials. etsy_client_id = keystring, etsy_client_secret
    # = shared secret. The x-api-key header is "{keystring}:{shared_secret}".
    etsy_client_id: str = ""
    etsy_client_secret: str = ""

    # Etsy OAuth 2.0 (PKCE).
    etsy_oauth_authorize_url: str = "https://www.etsy.com/oauth/connect"
    etsy_oauth_token_url: str = "https://api.etsy.com/v3/public/oauth/token"
    etsy_redirect_uri: str = "http://localhost:8000/api/auth/etsy/callback"
    etsy_scopes: str = "listings_r listings_w shops_r shops_w"

    # Where to send the browser back to after the OAuth callback completes.
    frontend_url: str = "http://localhost:3000"

    # Draft-listing defaults (Etsy requires these; the UI doesn't collect them yet).
    etsy_default_taxonomy_id: int = 1  # override with a real seller-taxonomy node id
    default_price: float = 5.00
    default_quantity: int = 999
    etsy_currency: str = "USD"
    etsy_default_section_title: str = "Listing Studio Drafts"
    etsy_who_made: str = "i_did"
    etsy_when_made: str = "made_to_order"
    etsy_listing_type: str = "download"  # digital products

    # Thumbnail preparation (rank=1 image is trimmed, padded, squared to size).
    thumbnail_padding_pct: int = 8
    thumbnail_size: int = 2000

    # Description templating (description is not free-generated by the LLM).
    description_template: str = "default"
    description_variables: bool = False

    # Shop-section auto-assignment. Off by default: never create sections in the
    # user's shop without permission.
    auto_create_sections: bool = False

    # Optional size-chart image appended to every listing (empty = skip).
    size_chart_image: str = ""

    # LLM provider (Anthropic) for vision analysis + content generation.
    # Key is read from the environment only, never hardcoded (see CLAUDE.md).
    llm_api_key: str = ""
    llm_model: str = "claude-haiku-4-5-20251001"

    # Object storage root for uploaded originals + processed derivatives.
    storage_dir: str = "./storage"

    # Global daily API budget (app-wide, Personal App = 5.000/day). Tenant budget is per-tenant.
    global_daily_limit: int = 5000

    # Shown in the UI (ToU requires a visible support email).
    support_email: str = "support@example.com"

    # Browser origins allowed to call the API directly (dev). Comma-separated.
    cors_origins: str = "http://localhost:3000"


@lru_cache
def _load_settings() -> Settings:
    """Build Settings from the environment / .env, cached for the process."""
    return Settings()


# Test-only override. When set, ``get_settings()`` returns this instance verbatim,
# bypassing .env *and* the ambient environment so tests never depend on — or reach —
# external configuration (e.g. a real LLM_API_KEY). Production leaves this ``None``.
_override: Settings | None = None


def set_settings_override(settings: Settings | None) -> None:
    """Install an isolated Settings instance (or clear it with ``None``)."""
    global _override
    _override = settings


def clear_settings_cache() -> None:
    """Drop the cached production settings so the next load re-reads the env."""
    _load_settings.cache_clear()


def get_settings() -> Settings:
    """Return the active settings: the test override if set, else the cached load."""
    if _override is not None:
        return _override
    return _load_settings()
